package networking.message;

public enum CommandType {
	SET_RALLY_POINT, MOVE_TO, ATTACK_THING, HARVEST_THING, BUILD_ROAD, BUILD_BUILDING, PLAN_BUILDING, STOP, RESEARCH, CRAFT_ITEM, PRODUCE_UNIT, SPAWN_THING, SET_GUARDING;
}
